### ISSUE TITLE
Code sample in Readme.md using a Delete action as an example

### ISSUE THREAD

**Issue by artiomchi** [T4MVC/T4MVC#101]
This is probably the least important issue in here, but I thought to bring it up anyway.

The readme file for the project references the following:

> e.g. instead of
> ````c#
> @Html.ActionLink("Delete Dinner", "Delete", "Dinners", new { id = Model.DinnerID }, null)
> ````
> T4MVC lets you write
> ````c#
> @Html.ActionLink("Delete Dinner", MVC.Dinners.Delete(Model.DinnerID))
> ````

One thing that always worried me about this is that it's a GET request to a Delete method. Could we change this to a Details action, or something similar, that would make sense for a GET request? :)

**Comment by davidebbo** [comment]
Fair point. Feel free to send PR on the readme and we can get that in.

**Comment by artiomchi** [comment]
Done! I'll do the same in the R4MVC project as well :)
