### ISSUE TITLE
Provide hook for processing asset paths

### ISSUE THREAD

**Issue by nickdurcholz** [T4MVC/T4MVC#105]
We have a need for replacing parts of asset paths, and I wanted to ask if such a change would be necessary and welcome before doing the work and sending a pull request.

The situation is this: nuget puts javascript in a Scripts folder. We have customers who run security scans on our app and demand that any violations be fixed; they aren't flexible in this, even if one of the scan rules doesn't make any sense.  One of their rules is "thou shall not serve anything from a folder named Scripts".  It is silly, but the bureaucracy demands sacrifice, so I can't argue.

Our build process has already resolved this by moving everything in Scripts to a folder named ClientSide, and we have overidden ProcessVirtualPath to change up the urls for the T4MVC Scripts classes.  However, we'd also like to use the Asset paths and T4MVC doesn't seem to have a mechanism to change those paths.

My first inclination is to create a ProcessAssetPath(string) function in T4MVCHelpers that would by default just return its argument.  Is that the best way to go about it?  Is there any reason you wouldn't want it added to the project?

**Comment by davidebbo** [comment]
Fixed in PR #106
