### ISSUE TITLE
Remove references to Codeplex site

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/T4MVC#11]
I noticed there are some links to the old Codeplex site in the comments at the top of the `.tt` file.  We also have some dead links in the `readme.md`.

@davidebbo - would you prefer a pull request for these changes, or can I commit straight to the master branch?

**Comment by davidebbo** [comment]
No need for PR! :)

**Comment by kevinkuszyk** [comment]
Closing as I think they've all gone now.
