### ISSUE TITLE
Broken links in readme.md

### ISSUE THREAD

**Issue by JendaPerl** [T4MVC/T4MVC#117]
Please fix the "Contribute: learn how on the Contributor page" link on https://github.com/T4MVC/T4MVC

**Comment by davidebbo** [comment]
This must have gotten lost in the transition from Codeplex a while back. Unfortunately, I'm not sure that this content still exists, as I don't see much on https://archive.codeplex.com/?p=t4mvc

**Comment by JendaPerl** [comment]
Well if it doesn't than maybe someone ought to write it again. :-)
I've got some updates that I might be able to (and will be given time to) merge into the current version and I'd like to make them available.

**Comment by davidebbo** [comment]
@JendaPerl definitely, if you want to update the readme.md, just send a PR and we'll merge that in. Thanks!

**Comment by JendaPerl** [comment]
If I knew the address of the page, I would. I don't and I don't think I am the right person to write the page. I would think you might want to write down what do you want people to do, when they decide to help with the project. :-)

**Comment by kevinkuszyk** [comment]
Hello folks.

Some good news - I had a dig into the CodePlex archive and the old wiki content is still there.  I've copied over the [contributing](https://github.com/T4MVC/T4MVC/wiki/Contributing) and [known issues](https://github.com/T4MVC/T4MVC/wiki/Known-Issues) pages.

I'm not sure how relevant all that content is, as it all pre-dates the move to GitHub.  @davidebbo when you get a minute can you cast your eyes over it?

@JendaPerl I've fixed the link in the home page, so you (and anyone else) can view that content now.  Thanks for spotting the dead links there!

@davidebbo there was also a page of twitter quotes from 2011 - 2013.  I'd say let's let that content go and remove the link from the readme?

**Comment by davidebbo** [comment]
@kevinkuszyk thanks a lot for updating this! I think the content is still mostly correct.
