### ISSUE TITLE
Page names way too long

### ISSUE THREAD

**Issue by mysteryx93** [T4MVC/T4MVC#119]
Just trying this out in a .NET Core 2.2 Razor Page. When I type Pages, it shows page names such as

C__Spiritual_Self_Transformation_WebsiteCore_RemoteHealingTech_Areas_Account_Pages_Forgot_Password

Is this the intended behavior?

**Comment by davidebbo** [comment]
Generally, T4MVC is not intended for .NET Core. There is a sibling project for core, though I'm not sure what its status is: https://github.com/T4MVC/R4MVC

**Comment by mysteryx93** [comment]
Perfect thanks

**Comment by mysteryx93** [comment]
Unfortunately R4MVC also has the same crazy long path names
