### ISSUE TITLE
Update to MVC 5.2.7

### ISSUE THREAD

**Issue by trailmax** [T4MVC/T4MVC#120]
MVC 5.2.7 has been out for a while, what do you think about updating? 
(I'm getting warning in my cshtml files that assembly version is incorrect since we've updated to 5.2.7)

I can do a PR for that - should be straight forward and problem-less.

**Comment by davidebbo** [comment]
Sounds good, if you send a PR, I can get that in.

**Comment by winecraft** [comment]
Can you also bundle some samples to scaffold partial/regular views, from a model. It would give new/devs. a base to update/learn enhance.

**Comment by trailmax** [comment]
@winecraft this is really out of scope for this ticket. Also I don't think you are in the right place for scaffolding of views.

**Comment by trailmax** [comment]
Awesome, thanks David. 
Can you please let me know when this hits nuget.org, so I can run updates on my systems?

**Comment by davidebbo** [comment]
Should be there already.
