### ISSUE TITLE
Assets Not Generate for Nested Files

### ISSUE THREAD

**Issue by TorreyGarland** [T4MVC/T4MVC#123]
Using VS 2019 Enterprise Edition and T4MVC 4.2.2 for a MVC 5 project.
Assets are still not being generated for nested CSS files generated from a SCSS file after bundling and minification.

**Comment by schifazl** [comment]
I have a very similar problem:
I had some CSS files in my project and the Assets were correctly generated.

Then I replaced the plain CSS files with SCSS files which are generating the .css and .min.css file with the Web Compiler extension.

Now my css files aren't added to the Assets anymore.

**Comment by schifazl** [comment]
This old pull request solved my problem! https://github.com/T4MVC/T4MVC/pull/113
I think it should be accepted and merged.

**Comment by davidebbo** [comment]
Thanks for helping revive that old PR which was missed. It's in now! v4.2.4.
