### ISSUE TITLE
VS 2019 Support

### ISSUE THREAD

**Issue by delroyh** [T4MVC/T4MVC#125]
Currently T4MVC is only available up to VS 2017, is there any plans to release it for VS 2019?

We're currently locked to VS 2017 for some products because of this.

Thanks

**Comment by delroyh** [comment]
I realize I put this issue on the wrong project. It shouldn't be on T4MVC, it should be on AutoT4MVC, the VS extension itself.

Apologies!

**Comment by davidebbo** [comment]
Great, I was about to respond that I didn't understand what was currently limiting it to the older VS!
