### ISSUE TITLE
Map files override js files (if in view folders)

### ISSUE THREAD

**Issue by worthy7** [T4MVC/T4MVC#126]
![image](https://user-images.githubusercontent.com/4762399/77398777-77a0f200-6deb-11ea-820c-85dde77655c3.png)

You can see that instead of it giving me just urls like "Update.js", it is accidentally giving "Update.js.map"

**Comment by davidebbo** [comment]
Do you have a repro? This project is minimally supported, but if you find the issue and send a PR, we can get it in.

**Comment by worthy7** [comment]
I can probably put something together, but not sure about to fix it myself.

If it's minimally supported, is it because people are doing things a
different way now? New tools?

**Comment by davidebbo** [comment]
Two reasons:

1. More and more people are switching to .NET Core, and T4MVC doesn't support it. There is a separate R4MVC project for Core: https://github.com/T4MVC/R4MVC (I'm not involved in it).
1. As the maintainer, I personally have limited time to work on it (but I will get some fixes in if they're important)

**Comment by worthy7** [comment]
Ok thanks, I'll just work around the issue instead then.
