### ISSUE TITLE
Lower case routes not working in all cases

### ISSUE THREAD

**Issue by InteXX** [T4MVC/T4MVC#129]
The generated code contains this class:

```vb
Public Class _ViewNamesClass
    Public ReadOnly Index As String = "Index"
    Public ReadOnly Welcome As String = "Welcome"
End Class
```
However, I've specified `<UseLowercaseRoutes>True</UseLowercaseRoutes>` in the settings.

To address this, I modified the `.tt` file slightly. I changed this:
https://github.com/T4MVC/T4MVC/blob/6edfc803513d521accc3fd39b2a5cde84dc49337/T4MVCVB/T4MVCVB.tt#L948-L951
...to this:
```c#
    foreach (var viewPair in viewsFolder.Views)
    {
        if (settings.UseLowercaseRoutes) {
            WriteLine("Public ReadOnly " + EscapeID(Sanitize(viewPair.Key)) + " As String = (\"" + viewPair.Key + "\").ToLowerInvariant()");
        } else {
            WriteLine("Public ReadOnly " + EscapeID(Sanitize(viewPair.Key)) + " As String = \"" + viewPair.Key + "\"");
        }
    }
```
The generated code, then, now looks like this:
```vb
Public Class _ViewNamesClass
    Public ReadOnly Index As String = ("Index").ToLowerInvariant()
    Public ReadOnly Welcome As String = ("Welcome").ToLowerInvariant()
End Class
```
Would this be the recommended approach?

**Comment by davidebbo** [comment]
Hmmm, I wonder why that never came up. But yes, that seems reasonable.

**Comment by InteXX** [comment]
Very good, thank you.
