### ISSUE TITLE
T4MVC in VS2022 Preview 3.1

### ISSUE THREAD

**Issue by GraemeSMiller** [T4MVC/T4MVC#133]
Does anyone know how I can make T4MVC TT templates generate in VS 2022 Preview 3.1

If I run TranformAllT4Templates or run Custom Tool on the file

It just generates the T4MVC.cs file with ErrorGeneratingOutput

We are currently using 2022 for everything apart from generating T4MVC which is annoying.

**Comment by davidebbo** [comment]
I've been a bit disconnected from the .NET world, so I don't have VS 2022 anywhere. Is there any specific error it's giving? I wonder if they changed anything in T4 handling in general.

**Comment by GraemeSMiller** [comment]
In Transform Text Templates output I just get
-------------------------------------
Transforming template T4MVC.tt with TextTemplatingFileGenerator ... failed.

The generate cs file just contains a single line ErrorGeneratingOutput

**Comment by davidebbo** [comment]
And you don't see anything in the error/warning pane?

**Comment by GraemeSMiller** [comment]
David,

On running transform template error list below appears.

![image](https://user-images.githubusercontent.com/2472587/131657254-d44d5f10-b184-470d-845b-268464364229.png)

**Comment by davidebbo** [comment]
Ok, so it's complaining about a lot of things. It should be possible to isolate to a very small repro that could demonstrate that something is broken in that VS version. You can have a go at it. Or I can try to find time over the long weekend.

**Comment by davidebbo** [comment]
Searching around, it may be the same rot cause as https://developercommunity.visualstudio.com/t/T4-Templates-in-VS2022-require-incompati/1472620, which looks like a general T4 issue. So worth following that discussion.

**Comment by davidebbo** [comment]
Actually, it says there is a fix coming and that they will update when it's available.

**Comment by GraemeSMiller** [comment]
Really appreciate you investigating. Thanks will keep an eye on that issue.

**Comment by GraemeSMiller** [comment]
This issue is fixed in Visual Studio 2022 Preview 4. Thanks for your help

**Comment by davidebbo** [comment]
Awesome, thanks for following up!
