### ISSUE TITLE
Update to MVC 5.2.9

### ISSUE THREAD

**Issue by vkirienko** [T4MVC/T4MVC#142]
Hi,

I'm getting warning in my cshtml files that assembly version is incorrect since we've updated to 5.2.9 (long time ago).
MVC 5.2.9 has been out for a while, and PR to bump MVC version was merged.

Would be it possible to produce new NuGet package that include PR?

Vlad

**Comment by davidebbo** [comment]
Interesting. I thought with the right config magic it was able to automatically move up.

I will look into making a new release, but I'm really rusty on .NET, so I might need some help! :)

**Comment by davidebbo** [comment]
I opened #143 to discuss building it. Feel free to jump in!

**Comment by vkirienko** [comment]
With assembly redirect in web.config everything works just fine. Only when I try to compile cshtml files I am getting these warnings. It is just not clean looking output.

------
ASPNETCOMPILER : warning CS1702: Assuming assembly reference 'System.Web.Mvc, Version=5.2.7.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' used by 'T4MVCExtensions' matches identity 'System.Web.Mvc, Version=5.2.9.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' of 'System.Web.Mvc', you may need to supply runtime policy

**Comment by davidebbo** [comment]
Ok, I pushed version 4.2.5 to NuGet. Can you give it a try?

**Comment by vkirienko** [comment]
Warnings are gone now. Everything works!

**Comment by davidebbo** [comment]
Great! Thanks for your contribution.
