### ISSUE TITLE
Building T4MVC with latest VS

### ISSUE THREAD

**Issue by davidebbo** [T4MVC/T4MVC#143]
I haven't done this in quite some years, and my .NET skills are not as sharp as they used to be :)

When I try to open the solution, it wants me to either update the solution to .NET fx 4.8, or install a targeting pack:

![image](https://github.com/T4MVC/T4MVC/assets/556238/d68819c0-a492-49e3-8baf-61dec702880b)

Is there a downside to to updating to 4.8? Would that make the assembly unusable for people with older versions?

**Comment by vkirienko** [comment]
Should not be. You are not using anything from 4.8 (and probably don't plan to use) to make it unusable for people with older versions.

**Comment by davidebbo** [comment]
Ok, I upgraded it to 4.8. I also had to remove `<add key="webpages:Version" value="3.2.9.0"/>` from web.config, as that was causing a runtime version conflict.
