### ISSUE TITLE
RedirectToAction to action marked with NonAction

### ISSUE THREAD

**Issue by migig** [T4MVC/T4MVC#17]
This doesn't work:

``` c#
public class MyAccessibleController {

   public virtual ActionResult Foo() {
        return RedirectToAction(MVC.MyInaccessibleController.Bar());
    }

}

public class MyInaccessibleController {

    [NonAction]
    public virtual ActionResult Bar() {
        return RedirectToAction(MVC.MyInaccessibleController.Baz());
    }

    [NonAction]
    public virtual ActionResult Baz() {
        // do stuff
    }

}
```

I get the weird error of "blah blah needs to be regenerated". But the real reason is the `[NonAction]` decorated actions are not processed.

Fine.

So, how do I get my actions to be processed by the tt, BUT, not allow them to be called by the user?

**Comment by davidebbo** [comment]
I don't think that's supported today, but we could extend the `[T4MVC]` attribute to make this work. Currently, it's only valid on classes, but we could make it valid on methods. It would override `[NonAction]`.

If you want to try making this chance, search for `NonActionAttribute` in the template, and for T4MVCAttribute.cs.

**Comment by davidebbo** [comment]
But wait, I don't think this will work at all. How can you redirect to an action that's marked as NonAction? Redirecting causes a redirect, and MVC will refuse to process it (nothing to do with T4MVC at this point).

**Comment by migig** [comment]
I agree.

The reason I want T4MVC to detect it, is so I get all the benefits of T4MVC, which I need to use for those actions.

So if I label it private/internal/protected or mark it [NonAction], then T4MVC won't pick it up. But if I don't, then T4MVC will pick it up, but the user will be able to access it.

It's an annoying limitation (of the runtime I suppose, not T4MVC). I suppose I need to do a rethink of my design.

**Comment by davidebbo** [comment]
Ok, closing here at this point, as there is no clear thing that could be done in T4MVC.
