### ISSUE TITLE
Fresh clone doesn't build

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/T4MVC#2]
I just tried to build a fresh clone, but there are 370 errors!

It looks like the `T4MVCExtensions` project's reference to `System.Web.Mvc` is broken.  Can I add it in as a nuget reference?  It will mean the nuget package will also take a dependency on `Microsoft.AspNet.Mvc`.  Also, any preference of versions?  It looks like there are references to both v3 and v4.

**Comment by davidebbo** [comment]
I'm actually not seeing this. If I build a fresh clone from VS, I don't get any errors. Maybe something is in my GAC that's not in yours. What do they errors look like?

**Comment by kevinkuszyk** [comment]
![image](https://cloud.githubusercontent.com/assets/2734580/5978089/1f46b548-a895-11e4-93fe-71927afb612c.png)

I'm on a new machine, so that could be it.  In MVC 3 I think the tools installer used to put the MVC DLL in the GAC?

**Comment by davidebbo** [comment]
I see, the difference is that I have System.Web.Mvc 3.0.0.0 in my GAC, while you probably only have 3.0.0.1.

```
D:\>gacutil -l system.web.mvc
Microsoft (R) .NET Global Assembly Cache Utility.  Version 4.0.30319.33440
Copyright (c) Microsoft Corporation.  All rights reserved.

The Global Assembly Cache contains the following assemblies:
  system.web.mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  system.web.mvc, Version=3.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  system.web.mvc, Version=4.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  system.web.mvc, Version=5.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL
  system.web.mvc, Version=5.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL

Number of items = 5
```

I just tried removing the System.Web.Mvc reference and re-adding 3.0.0.1 via NuGet (`Install-Package microsoft.aspnet.mvc -Version 3.0.50813.1`), but I'm still getting a build error:

```
Assembly 'T4MVCExtensions, Version=3.0.0.0, Culture=neutral, PublicKeyToken=null' uses 'System.Web.Mvc, Version=3.0.0.1, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version than referenced assembly 'System.Web.Mvc, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'  d:\Code\Codeplex\T4MVC\T4MVCExtensions\bin\Debug\T4MVCExtensions.dll    T4MVCHostMvcApp
```

I'm not sure why it says we're still referencing 3.0.0.0!

**Comment by davidebbo** [comment]
Ok, I see the problem. I'll fix shortly

**Comment by davidebbo** [comment]
Ok, please verify!

**Comment by kevinkuszyk** [comment]
Thanks - that's fixed it.
