### ISSUE TITLE
MVC3 dlls in a MVC4 project

### ISSUE THREAD

**Issue by dlaptin** [T4MVC/T4MVC#21]
Installing T4MVC from nuget in an ASP.NET MVC4 project I got a lot of old dlls added to the project including System.Web.Mvc.dll version 3 and other.

**Comment by davidebbo** [comment]
Do you mean it's actually overwriting your MVC4 DLLs by MVC3 in your bin folder? It shouldn't be doing that.

**Comment by davidebbo** [comment]
To elaborate, the [T4MVCExtensions package](http://www.nuget.org/packages/T4MVCExtensions/) has a NuGet reference to MVC3. But if your project has a NuGet reference to any newer version of MVC, that should take precedence over that one.

**Comment by dlaptin** [comment]
You are right. There was a bad reference to the MVC4 dll in my project. 
As soon as I fixed this T4MVC  installed correctly.

Thank you!
