### ISSUE TITLE
Changing the ProcessVirtualPathDefault method to keep the Tilde has unwanted side-effects.

### ISSUE THREAD

**Issue by jordangurney** [T4MVC/T4MVC#34]
However, I did have one question: I modified the ProcessVirtualPathDefault(string virtualPath) method to include the ASP.NET tilde, because I wanted to use the Links.Content.css.whatever_css inside of my BundleConfig.cs file for css and JS bundling. And that file NEEDS the tilde. However, when I use the @Links.Content... in my VIEWS, the tilde is there and ASP.NET doesn't get a chance to resolve it before it hits the browser, and then the browser doesn't know what to do with it. The resource is thus, not found until the tilde is removed. Right now, I'm solving it in a really sloppy way, I wrote an extension method that trims off of the character of the string if it's a tilde for the VIEWS, but do you have a more elegant solution? Surely this is something others (even yourself) have run into before???

**Comment by davidebbo** [comment]
It's a tricky one. In the end, path that are meant for server used are not the same thing as path that are meant for client use. Right now, T4MVC is generating paths for the client (without the tilde). We could generate two sets of paths (e.g. `Links.Content` vs `ServerLinks.Content`, but that seems a bit messy.

Maybe others will have other ideas.

**Comment by jordangurney** [comment]
What about a built-in extension method, like the one I wrote to solve this? So that it's documented and others don't have to figure out a way to solve it own their own?

```
public static string RemoveAspNetTilde(this string input)
        {
            if (!String.IsNullOrWhiteSpace(input) && input[0] == '~')
                input = input.Replace("~", "");
            return input;
        }
```

**Comment by jordangurney** [comment]
OR, have a way for the ASP.NET engine to resolve the tilde before it sends it to the client. Just like writing a path with a tilde in my views in strings? <img src="~/Content/images.... resolves just fine by ASP.NET, one would think that the string generated by T4MVC would create the same behavior. I'm guessing it's an order of operations thing.

**Comment by davidebbo** [comment]
In the old days, ASP.NET was only doing that for WebForms on tags that had `runat=server`. But I think you're right that in more recent releases, when using Razor, they might do it for all such tags. Tough if that's the case, you would not end up with tildes coming back to the client, yet you mentioned that you did have that problem. There should be nothing magical about the T4MVC strings. e.g. it's the same as assigning a string to a variable and using that in the view.

Sorry, I'm just not up to date on exactly how Razor processes these paths.

**Comment by jordangurney** [comment]
Or this could be used. http://webactivedirectory.com/asp-net/asp-net-use-url-content-from-razor-to-resolve-relative-urls/

**Comment by jordangurney** [comment]
With the Solution above, i.e. using Url.Content to resolve URL's with the Tilde, that actually works quite  nicely after I tested this for myself!

So I'm going to keep my changes to the T4MVC.tt.hooks.t4 file to comment out the VirtualPathUtility.ToAbsolute(virtualPath); in the ProcessVirtualPathDefault method. This KEEPS the tilde's which I need if I want to use the Links.Content.css.... and Links.Scripts.jquery_version2_x_js capabilities that T4MVC offers in my BundleConfig.cs file (which is pretty big). And, all I do on the web pages is <a href="@Url.Content(Links.Content.images.ajax_loader_gif)"

**Comment by jordangurney** [comment]
This, by the way, seems like the cleanest, and most consistent solution as you need Html Helpers for other types of links in T4MVC anyway (i.e. href="@Url.Action(MVC.Home.Index())").

**Comment by davidebbo** [comment]
Agreed, that feels like a good solution. Thanks for sharing!

**Comment by kevinkuszyk** [comment]
@jordangurney - we already have what you're looking for I think.  Check the `Links.Bundles` constants added in v3.13.0 (PR #7):

```
Links.Bundles.Content.Assets.foo_css
```

@davidebbo - apologies - I didn't get time to update the docs yet.

**Comment by davidebbo** [comment]
Ah right, totally forgot about that! Yes, we should doc it :)

**Comment by kevinkuszyk** [comment]
The [wiki page](https://github.com/T4MVC/T4MVC/wiki/Documentation#support-for-mvcs-script-and-style-bundles) is now updated, and I also [pushed an update](https://github.com/T4MVC/T4MVC/commit/59938835d439bbfb3b19b8240bcf310f8dfd7eb9) to the sample app so that the `BundleConfig.cs` matches the wiki.

**Comment by jordangurney** [comment]
Thanks guys! That's a much better solution. I'll just have to schedule that into our dev cycle to change everything around to use it. But it'll be worth it in the end.

Thanks,
Jordan
