### ISSUE TITLE
Avoid "Run Custom Tool" every time I add a resource

### ISSUE THREAD

**Issue by jordangurney** [T4MVC/T4MVC#35]
Forgive me if this question has already been answered. I haven't found it. 

Every time I add a new resource (an image, let's say), I have to right click the tt file for T4MVC and select "Run Custom Tool". I'm just wondering if there's a way to have it run automatically, as soon as it detects that I've made a change to the MVC project file by adding a new resource?

**Comment by davidebbo** [comment]
You should check out [autot4mvc](https://visualstudiogallery.msdn.microsoft.com/8d820b76-9fc4-429f-a95f-e68ed7d3111a). It's a separate project that aims to solve this problem.
