### ISSUE TITLE
GeneratedCodeAttribute missing for static field

### ISSUE THREAD

**Issue by neredera** [T4MVC/T4MVC#37]
The [GeneratedCode] Attribute is missing for static fields.

For example it is missing for 'ActionNamesClass s_actions'.

https://github.com/T4MVC/T4MVC/blob/master/T4MVCHostMvcApp/T4MVC%20Files/T4MVC.tt#L283

**Comment by davidebbo** [comment]
Feel free to send PR for that, thanks!

**Comment by davidebbo** [comment]
Fixed in #63
