### ISSUE TITLE
System.InvalidOperationException: the snapshot is out of date and cannot be used anymore because the type tree has been updated.

### ISSUE THREAD

**Issue by jordangurney** [T4MVC/T4MVC#38]
I have no idea what caused, this extremely mission-critical, extremely annoying bug that I cannot find any answers for on Google. All of the sudden, out of the clear blue sky my ASP.NET MVC 5 web application wouldn't Build. The error it gave me (just one error), is 

"Running transformation: System.InvalidOperationException: The snapshot is out of date and can not be used anymore because the type tree has been updated. A new snapshot needs to be acquired.
   at Microsoft.RestrictedUsage.CSharp.Semantics.DefinitionsInterop.MemberDefinition_GetReturnType(Handle treeHandle, Int32 assemblyId, IntPtr typeId, Int32 memberIndex, Handle& handle)
   at Microsoft.RestrictedUsage.CSharp.Semantics.MemberDefinitionInfo.get_ReturnType()
   at Microsoft.RestrictedUsage.CSharp.Semantics.MemberDefinitionInfoWithCache.get_ReturnType()
   at Microsoft.VisualStudio.CSharp.Services.Language.CodeModel.CCodeFunction.get_Type()"

It then reports several lines of problematic code: T4MVC.tt:line 1992, T4MVC.tt:line 2093, T4MVC.tt:line 1996 and T4MVC.tt:line 238.

This is preventing me from publishing changes from my Visual Studio solution to my production website - which is in need of extremely mission-critical hotfixes. 

Can anyone PLEASE help??? :(

**Comment by davidebbo** [comment]
Came up on http://t4mvc.codeplex.com/discussions/540746. Try workarounds from there. It seems to be related to AutoT4MVC, which is a separate project (https://github.com/bennor/AutoT4MVC), so closing here.

**Comment by jordangurney** [comment]
Just a thought on this - I asked about how one can auto-build the T4 template whenever I add a new resource and AutoT4MVC was suggested to me. Now that I've lost hours of research on this bug, I would gladly go back to the way things were before AutoT4MVC if I would have known that it would have caused such a tremendous nightmare. Maybe in the future, a fellow seeker of automated T4 template builds ought to at least be aware of this potential issue with AutoT4MVC if that tool is going to be suggested.

Just a thought :)

**Comment by davidebbo** [comment]
I don't own AutoT4MVC, and I'm really not familiar with it. If it's found to be 100% broken, then indeed, people should not use it. My understanding is that tit works for some. But it's best to discuss that there than here, so the owners see it.

**Comment by jordangurney** [comment]
Ok, good point.
