### ISSUE TITLE
COMException when compiling my project

### ISSUE THREAD

**Issue by RufusJWB** [T4MVC/T4MVC#39]
The latest build of T4MVC throws the following exception, when compiling a project:

> Error Running transformation: System.Runtime.InteropServices.COMException (0x80004005): The item 'T4MVC1.cs' cannot be deleted.
> 
> Server stack trace: 
>    at EnvDTE.ProjectItem.Delete()
>    at Microsoft.VisualStudio.TextTemplatingA9FF74483014B91731C5A3FE77649210D48CD466F77D91AA8217419745FB42BE9F31A891F68DB3CB21E5B288A38947C45C721BB79780F6C1CF2C75436039A996.GeneratedTextTransformation.Manager.VSManager.ProjectSync(ProjectItem templateProjectItem, IEnumerable`1 keepFileNames) in c:\Daten von Rufus\SimpleOpenCMDB\SimpleOpenCMDB\T4MVC.tt:line 2785
>    at Microsoft.VisualStudio.TextTemplatingA9FF74483014B91731C5A3FE77649210D48CD466F77D91AA8217419745FB42BE9F31A891F68DB3CB21E5B288A38947C45C721BB79780F6C1CF2C75436039A996.GeneratedTextTransformation.Manager.VSManager.<.ctor>b__74(IEnumerable`1 keepFileNames) in c:\Daten von Rufus\SimpleOpenCMDB\SimpleOpenCMDB\T4MVC.tt:line 2770
>    at System.Runtime.Remoting.Messaging.StackBuilderSink._PrivateProcessMessage(IntPtr md, Object[] args, Object server, Object[]& outArgs)
>    at System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(IMessage msg, IMessageSink replySink)
> 
> Exception rethrown at [0]: 
>    at System.Runtime.Remoting.Proxies.RealProxy.EndInvokeHelper(Message reqMsg, Boolean bProxyCase)
>    at System.Runtime.Remoting.Proxies.RemotingProxy.Invoke(Object NotUsed, MessageData& msgData)
>    at System.Action`1.EndInvoke(IAsyncResult result)
>    at Microsoft.VisualStudio.TextTemplatingA9FF74483014B91731C5A3FE77649210D48CD466F77D91AA8217419745FB42BE9F31A891F68DB3CB21E5B288A38947C45C721BB79780F6C1CF2C75436039A996.GeneratedTextTransformation.Manager.VSManager.Process(Boolean split) in c:\Daten von Rufus\SimpleOpenCMDB\SimpleOpenCMDB\T4MVC.tt:line 2741
>    at Microsoft.VisualStudio.TextTemplatingA9FF74483014B91731C5A3FE77649210D48CD466F77D91AA8217419745FB42BE9F31A891F68DB3CB21E5B288A38947C45C721BB79780F6C1CF2C75436039A996.GeneratedTextTransformation.TransformText() in c:\Daten von Rufus\SimpleOpenCMDB\SimpleOpenCMDB\T4MVC.tt:line 432   c:\Daten von Rufus\SimpleOpenCMDB\SimpleOpenCMDB\T4MVC.tt   2785

I wonder if it has to do something with this issue: https://github.com/T4MVC/T4MVC/issues/24

**Comment by RufusJWB** [comment]
Uninstalling T4MVC and reinstalling it from the Nuget server solved my problem. Strange. I'll close this ticket.

**Comment by MrChriZ** [comment]
bizarre I've just ran into the same thing - same fix - simply upgrading it worked for me.
