### ISSUE TITLE
ASP.NET 5 Support

### ISSUE THREAD

**Issue by Daniel15** [T4MVC/T4MVC#41]
Does T4MVC support ASP.NET 5 + ASP.NET MVC 6? Would it be difficult to add?

**Comment by davidebbo** [comment]
There is a separate project that was started to tackle that problem. See https://github.com/T4MVC/R4MVC for details.

**Comment by Daniel15** [comment]
Does it work? Are there instructions on how to use it?

**Comment by davidebbo** [comment]
I'm not directly involved with it myself, so please ask for any help of there. Thanks!

**Comment by kevinkuszyk** [comment]
> Does it work?

No, not at the moment.  It was building against an earlier beta (3 or 4 I think from memory), but I'm having problems building against the latest betas.

> Are there instructions on how to use it?

Not yet.  We are focused on getting a working product first.  For v1 we are aiming to support most of the common use cases for T4MVC (see [this discussion](https://github.com/T4MVC/R4MVC/issues/15)).  The generated API surface will be the same as T4MVC, enabling easy migration.  Most of the docs will probably be lifted from the T4MVC [wiki](https://github.com/T4MVC/T4MVC/wiki/Documentation) (thanks @davidebbo!)

As with many project maintainers, we have many demands on our time.  We welcome contributors, so if you are able to help out, please check our [issues list](https://github.com/T4MVC/R4MVC/issues) and open a pull request for the feature you want to work on.
