### ISSUE TITLE
Problem with views sub-folder containing dot

### ISSUE THREAD

**Issue by Ezeckiel2517** [T4MVC/T4MVC#51]
In the Views folder I have a sub-folder that had a dot in its name. It is not a controller, of course, but contains some templates shared between several projects. For that reason, I cannot simply rename it.

In that scenario, T4MVC will generate a class that doesn't compile, as classname cannot contains a dot.
Any ideas to solve this? I don't think there is an exclude folder settings. Or maybe the class name generation should be fixed?

I'm thinking about modifying the method ProcessAllViews.

**Comment by davidebbo** [comment]
Fixed in 3.16.2. Please verify.

**Comment by Ezeckiel2517** [comment]
Yes it was well fixed
