### ISSUE TITLE
Move off T4MVC for vNext

### ISSUE THREAD

**Issue by waynebrantley** [T4MVC/T4MVC#56]
What is the vNext story?
I am considering the painful choice of dropping T4MVC in vnext.  I would really miss it though.
There are existing issues around Async in T4MVC and the issue list just grows with the move to vNext.
Additionally, I end up with magic strings in my javascript anyway.

With Rosyln, potentially that would be a better way to generate this kind of information?

This ticket is to discuss plans for the future of T4MVC (or its demise)

**Comment by davidebbo** [comment]
There is a parallel project that others are driving for aspnet 5, though not sure what state it's in. See https://github.com/T4MVC/R4MVC.

**Comment by kevinkuszyk** [comment]
@waynebrantley - @wwwlicious and I started working on  R4MVC when ASP.net 5 projects looked to be dropping support for T4 templates.  The goal was to build a Roslyn powered equivalent to T4MVC, with compatible generated code to make switching from T4MVC as easy as possible.

Now that T4 support is in the works and coupled with other work commitments, R4MVC is less of a priority for me.

If it's something that you have time to contribute to, lets continue the conversation in the R4MVC repro.
