### ISSUE TITLE
Missing parameterless default method for actions with completely optional parameters

### ISSUE THREAD

**Issue by DoctorVanGogh** [T4MVC/T4MVC#59]
Imagine a controller

``` csharp
    public partial class FooController : Controller {
        public virtual ActionResult RequiredParamAction(object foo) {
            return View();
        }

        public virtual ActionResult OptionalParamAction(object foo = null) {
            return View();
        }

        public virtual ActionResult NoParamAction() {
            return View();
        }
    }
```

T4MVC will only generate (parameterless) action stubs for methods `RequiredParamAction` & `NoParamAction`, so ultimately you can use `var someaction = MVC.Foo.RequiredParamAction()`& `var someaction = MVC.Foo.NoParamAction()`, but **never** `var someaction = MVC.Foo.OptionalParamAction()`.
That last statement will always fall back to the actual `FooController` method, and execute the original action - which is unexpected and error-prone.

The reason for the missing stub(s) is [this filter](https://github.com/T4MVC/T4MVC/blob/master/T4MVCHostMvcApp/T4MVC%20Files/T4MVC.tt#L1867) (invoked [here](https://github.com/T4MVC/T4MVC/blob/master/T4MVCHostMvcApp/T4MVC%20Files/T4MVC.tt#L1875) and [here](https://github.com/T4MVC/T4MVC/blob/master/T4MVCHostMvcApp/T4MVC%20Files/T4MVC.tt#L1883)).
I did a quick test and replaced the predicate with a sufficiently initialized `m => !m.HasParameters` and the expected parameterless stub(s) get correctly generated.

---

Of course you get a warning that the parameterless overload is hiding the overload with the completely optional parameters, but this should not affect routing, since the parameterless method is tagged with a `[NonAction]` attribute.

I can see unexpected behavior (a call to the T4MVC method), if the action is manually invoked without any parameters, but I cannot see a regular use-case for that. 
Calling [RenderAction](https://msdn.microsoft.com/en-us/library/system.web.mvc.html.childactionextensions.renderaction%28v=vs.118%29.aspx) would go through the routing engine, and filter out the non-action overload, so ultimately this would only affect custom invocations.

Those manual calls _could_ be worked around, if you added a 'dummy' parameter to the action and passed some value for that. Not nice, or legacy friendly, but at least it's possible to use both T4MVC _and_ call the action. 
If you don't generate the overload, you may be able to directly call the action, but you can't use T4MVC to refer the action without passing all parameters - _ever_.

---

Since according to the git history the filter predicate is part of the original mvc contrib project there's maybe some other reason, why methods with purely optional parameters get skipped.
I've made some local changes to my T4 to enable stub generation in those cases - If you think this makes sense in a global setting, I'll happily submit a PR, but maybe this needs a toggle setting with the new behavior disabled, to preserve legacy compatibility.

**Comment by davidebbo** [comment]
Note that T4MVC generates two different types of things:
1. In a partial class, it sometimes adds parameterless overloads (which become part of the actual user class)
2. In a derived class, it overrides all the action methods that came from the base

In the case of `OptionalParamAction`, it won't do 1., but it will do 2. That means that if you call `var someaction = MVC.Foo.OptionalParamAction()`, you end up really calling the T4MVC overload.

Can you explain exactly what's not working? I may not be seeing all angles.

**Comment by DoctorVanGogh** [comment]
Hmm, I did initially write what felt like three pages of examples and tables of needed overloads...

But I took another look at a simplified project, an noticed the default T4MVC does exactly as you described and performs as expected, so this whole issue might have been a misdiagnosed error on my part (overrides, default parameters & missing 'MVC.' before referring to an action).

Basically I had gotten a non `IT4MVCActionResult` injected into my views, and assumed it was because the compiler had resolved a parameterless call to the base method definition.... I'll take another look at my larger project, but this may have been a non-issue.

**Comment by davidebbo** [comment]
Closing for now. We can re-open or start new issue as needed.
