### ISSUE TITLE
Templates generated in VS 2015 after update 1 doesn't compile when controllers with generic inheritance

### ISSUE THREAD

**Issue by diegoe-lynkos** [T4MVC/T4MVC#60]
Hi,
I was working with T4MVC (version 3.16.0) in VS 2015 community edition without any problems. However, after I updated my VS2015 with the update 1, T4MVC started to generate some code that doesn't compile, but only in those controllers that inherits from a generic and abstract one.

For instance, in this situation:

```
public abstract class BaseController<T> {
    ....
    public virtual ActionResult BaseAction(int baseParameter) { }
}


public partial class SomeController : BaseController<T> {
    .....
    public virtual ActionResult SomeAction(int someParameter) { ..... }
}
```

then, the code generated by T4MVC for the parameters of the action "SomeAction" compiles, but for some reason the code for the parameters of the BaseAction method are replaced in the template by an empty string.

This capture shows this in my code:
![capture](https://cloud.githubusercontent.com/assets/16402886/11958654/bf6d3b74-a8a7-11e5-9ff1-391c6940b6aa.PNG)

AccountStatement_Download is defined in the subclass (the controller that is not abstract), and the other three methods are defined in the superclass (the abstract controller with a generic type).

I already tried updating T4MVC to the last version released yesterday (3.17.0) but the error persists.

I also tried to regenerate the templates in another machine with VS 2015 without the update 1 installed, and it worked.

**Comment by davidebbo** [comment]
Most likely the same as #54, for which there is a VS patch. Try https://msdn.microsoft.com/en-US/library/mt634751(VS.140).aspx

**Comment by diegoe-lynkos** [comment]
It really was the same problem! The patch fixed it.
Thank you!
