### ISSUE TITLE
Add an up-for-grabs label?

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/T4MVC#66]
@davidebbo do you think there's some value in having an `up-for-grabs` label here or are all issues up for grabs in your mind?

I was thinking about issues like #64 and #65 which I would do if I had the time, but unfortunately I don't at the moment.

**Comment by davidebbo** [comment]
I think they're pretty much all up for grab. Though some are more important than others, and a label could help prioritize.

**Comment by kevinkuszyk** [comment]
I've made that label and added it to  #64 and #65.  Can you add it to your higher priority issues?

**Comment by davidebbo** [comment]
I don't really have a list, and unfortunately very little time to go through. But let's start with those two :)

**Comment by kevinkuszyk** [comment]
I know the feeling....
