### ISSUE TITLE
Generated code for ActionResult contains parameter without name

### ISSUE THREAD

**Issue by mnmr** [T4MVC/T4MVC#67]
T4MVC, in our solution, generates an ActionResult and FileResult that do not compile. The problem is that no parameter name is supplied for the override methods (ExecuteResult and WriteFile, respectively).

I have fixed the problem locally by modifying line 2076 (version 3.17.1) in the WriteFormalParameters method to this:
`TT.Write(p.Type + " " + (string.IsNullOrEmpty(p.Name) ? "foo" : p.Name));`

**Comment by davidebbo** [comment]
Can you share more details about what the code that causes the situation looks like? Also, if you have a fix, please feel free to send PR.

**Comment by mnmr** [comment]
Pull request sent. 

I'm not sure what could be cause, as the faulty code are basic ActionResult/FileResult classes that are independent of the controllers. All I can think of that might influence T4MVC is that we inherit from a BaseController residing in a separate project.

**Comment by kevinkuszyk** [comment]
@mnmr what version on Visual Studio are you on?  This sounds similar to #54 which was caused by a bug in VS 2015.1.

**Comment by mnmr** [comment]
@kevinkuszyk It does indeed sound like #54 (and we are using 2015u1).

**Comment by kevinkuszyk** [comment]
Give this hotfix a try if you don't already have it on: 
https://msdn.microsoft.com/en-US/library/mt634751(VS.140).aspx

I think there is also an update rollup now which has it in too.

**Comment by davidebbo** [comment]
Yes, that's probably it. Closing for now, but we can reopen if that's not it.
