### ISSUE TITLE
Build errors after transforming T4 templates

### ISSUE THREAD

**Issue by mmoore99** [T4MVC/T4MVC#73]
I have an application that uses T4MVC that is now getting build errors after transforming the T4 templates.  Please see the screen shots included below that show the diffs between the old and new generated files where the errors are occurring.  Please advise if there is additional information needed regarding this The version of T4MVC is 3.15.2. Visual Studio 2015.  Asp.net MVC 5.x.

![screenclip](https://cloud.githubusercontent.com/assets/45022/13942875/785d538c-efb4-11e5-8a03-5937dfd0b547.png)

![screenclip 1](https://cloud.githubusercontent.com/assets/45022/13942869/6ad49f68-efb4-11e5-80a6-7eca3b5e0274.png)

![screenclip 2](https://cloud.githubusercontent.com/assets/45022/13942877/7e869106-efb4-11e5-876a-7627b2b432fa.png)

**Comment by kevinkuszyk** [comment]
Did you recently upgrade to VS 2015 Update 1?  If so, you'll need to install a [hotfix](https://msdn.microsoft.com/en-US/library/mt634751%28VS.140%29.aspx) (see #54 for more details).

**Comment by mmoore99** [comment]
> If so, you'll need to install a hotfix (see #54 for more details).

Thanks, that solved the problem.

**Comment by davidebbo** [comment]
I really wish they'd push that update on everyone automatically...

**Comment by kevinkuszyk** [comment]
> I really wish they'd push that update on everyone automatically...

@davidebbo can you pull some strings to make that happen?  I guess it will be in update 2 so this should go away soon?

**Comment by davidebbo** [comment]
@kevinkuszyk I had tried at the time, but I guess in the grand order of things, it doesn't affect many (non-T4MVC) users. Yes, it should be in the next update, and I don't have any insider info on when that will be :)
