### ISSUE TITLE
CI Server?

### ISSUE THREAD

**Issue by kevinkuszyk** [T4MVC/T4MVC#8]
I've setup R4MVC on [AppVeyor](https://ci.appveyor.com/project/T4MVC/r4mvc).  Any objections if I add T4MVC too?

**Comment by davidebbo** [comment]
I'm all for it! Is AppVeyor free? I've never used it, but would love to learn more about it.

**Comment by kevinkuszyk** [comment]
Yes, it's free for open source projects.  It's a little slow sometimes as they provision a new Azure VM for each build, but the product is very good.

You should be able to login at http://www.appveyor.com using your GitHub creds.  I've made the Owners team on GitHub admins over on AppVeyor.

Let me know if that works and I'll close this issue down.

It looks like there's still a problem with the MVC dependencies:
https://ci.appveyor.com/project/T4MVC/t4mvc/build/4#L105

I'll raise a seperate issue for that, and have a look at it when I get some time.

**Comment by davidebbo** [comment]
Great, I'm able to access it!

I can help look at the build issue later.

**Comment by kevinkuszyk** [comment]
Thanks!
