### ISSUE TITLE
why T4MVC makes all class to Partial And All Action To Virtual?

### ISSUE THREAD

**Issue by ehsanehsani** [T4MVC/T4MVC#85]
After install T4MVC on my Project i Found Out All Class Have Changed to Partial Class And All Action Have Changed to Virtual.
 For example : public virtual ActionResult index
why this happens?

**Comment by davidebbo** [comment]
This [old post](https://blogs.msdn.microsoft.com/davidebb/2009/06/25/mind-if-my-mvc-t4-template-changes-your-code-a-bit/) is from 2009, but still correctly describes the design.
