### ISSUE TITLE
Does not build 4.51 and vs 2015

### ISSUE THREAD

**Issue by papyr** [T4MVC/T4MVC#87]
Hi, this does not build with target 4.51 or 4,52 with VS 2015 and web pages 3.0

**Comment by kevinkuszyk** [comment]
Hi @papyr T4MVC does work with .net 4.5.1 and 4.5.2 and Razor / Web Pages 3.x.  I double checked here with morning with File > New Project in VS 2015.

Can you post a screen shot or details of the build error you are seeing?  Maybe there is something else in your solution which is causing the build error or conflicting with T4MVC.
