### ISSUE TITLE
T4MVCExtensions does not seem to work with binding redirect

### ISSUE THREAD

**Issue by monemihir** [T4MVC/T4MVC#88]
I have a project X which is a class library referencing T4MVCExtensions 3.0.0 and then I have a project Y which is a web project referencing T4MVCExtensions 3.17.5.

When I try to run the web project it gives me a version mismatch error.

Binding redirect does not seem to work since the file version is still 3.0.0.0 even though the package is actually at 3.17.5.

What am I missing here?

**Comment by davidebbo** [comment]
The assembly version is always 3.0.0.0, so there should never be a need for binding redirects.

**Comment by monemihir** [comment]
I think it is happening since v3.0.0 is not strong named. 

Since what version did you start strong naming?

**Comment by davidebbo** [comment]
Looks like it was around 3.6, so way back in early 2013. Do you think you're dealing with something that old?

**Comment by davidebbo** [comment]
Actually, it was 3.5. See 13f13aa31ab9b0f5c111a354fc24caf51ea46f20. Pretty old stuff. Sorry, I guess you won't be able to use both pre and post together.

**Comment by monemihir** [comment]
I just want to reference the oldest version that would work to keep max compatibility. 

I can recompile the offending project source code with updated version of the extensions lib. 

So you reckon v3.6 was when you started strong naming?

**Comment by monemihir** [comment]
Ahh great thanks will check.
