### ISSUE TITLE
Errors when running sample host web app

### ISSUE THREAD

**Issue by ZmorzynskiK** [T4MVC/T4MVC#90]
Hi,

I just forked T4MVC and wanted to play with it, but it looks like there're some errors that I get when running in VS2015 with Ctrl+F5:

1. this is the first one:
```
Invalid pattern: 'bootstrap*.css'. Wildcards are only allowed in the last path segment, can contain only one leading or trailing wildcard, and cannot be used with {version}.
Parameter name: virtualPath
```

2. when I comment line 13 in `BundleConfig.cs` and then run, I get different error:
```
Multiple types were found that match the controller named 'Home'. This can happen if the route that services this request ('{controller}/{action}/{id}') does not specify namespaces to search for a controller that matches the request. If this is the case, register this route by calling an overload of the 'MapRoute' method that takes a 'namespaces' parameter.

The request for 'Home' has found the following matching controllers:
T4MVCHostMvcApp.SomePortableArea.Controllers.HomeController
T4MVCHostMvcApp.Controllers.HomeController
T4MVCHostMvcApp.Areas.Home.Controllers.HomeController

```
3. and then when I added `namespaces` to `RegisterRoutes` in `Global.asax` I get another error:
```
Links.Bundles.Content does not contain a definition for Styles
```
that points to this line in `Site.Master`:
```
<%= Styles.Render(Links.Bundles.Content.Styles) %>
```
which indeed is invalid and I believe it should be something like:
```
    <%= Styles.Render(Links.Bundles.Styles.common) %>
    <%= Styles.Render(Links.Bundles.Styles.bootstrap) %>
```
(given that bootstrap file is being used).

Anyone experienced that? I'll create pull request that fixes those issues.

cheers,
Krzysztof

**Comment by ZmorzynskiK** [comment]
Pull request is here: #91

**Comment by davidebbo** [comment]
Thanks for the fix. Admittedly, this sample app is a bit of a monster, and not really meant to be run. Instead, the workflow has been more to look at the diff in the generated files as the .tt file evolves, and make sure it all makes sense. But it doesn't hurt to make it runnable as well :)
