### ISSUE TITLE
T4MVC on Build Server

### ISSUE THREAD

**Issue by ThunderSizzle** [T4MVC/T4MVC#93]
I'm setting up my first CI server with TeamCity. However, I was able to get the project to run T4 templates, but when ran, since it was part of MSBuild instead of VS, T4MVC threw the error "Could not find the VS Project containing the T4 file."

Maybe I'm doing it wrong, but the internet is relatively quiet about CI and T4MVC. I did try using various command line calls to open VS and execute the T4 templating, which works, except never finishes (e.g. VS never closes). 

So, this may be a non-issue if there actually is a way to implement CI and T4MVC right now, and if so, I'd be much obliged if someone could point me to it, but if there's not, I'm posting this as an issue, I guess, since I don't see any other tickets referencing this. Thanks!

**Comment by davidebbo** [comment]
Sorry, that is not a supported scenario. Same as #76.

**Comment by davidebbo** [comment]
I should add that the common pattern is to do the generation at design time, and then commit those generated .cs files. When doing that, CI works fine.
