### ISSUE TITLE
Invalid generic types in VS2017 RC

### ISSUE THREAD

**Issue by augi** [T4MVC/T4MVC#94]
If action parameter type is generic type then the generated action method signature contains type without namespace.

Original action method: `ActionResult MyAction(MyGeneric<AType> par)`

Generated code in VS2015: `ActionResult MyAction(MyOrg.MyGeneric<MyOrg.AType> par)`
So namespaces are correctly added because there is no `using` related to custom code.

Generated code in VS2017 RC: `ActionResult MyAction(MyOrg.MyGeneric<AType> par)`

Please note that `MyOrg.` is missing for the generic parameter type. So the code cannot be compiled (because `using` is not added neither).

It looks like behavior of [EnvDTE.CodeTypeRef](https://msdn.microsoft.com/library/envdte.codetyperef.aspx) was changed - the `AsString` and `AsFullName` properties return different values in VS2017 RC and T4MVC doesn't reflect that change.

I also [reported this as a bug in Visual Studio](https://connect.microsoft.com/VisualStudio/feedback/details/3120651) - the behavior of this crucial interface shouldn't be changed IMHO.

**Comment by davidebbo** [comment]
Darn, that sounds like a bad breaking change in DTE behavior. Thanks for isolating it and reporting it (voted!). Hopefully they can solve this before the final 2017, which is not far out.

**Comment by augi** [comment]
I've just updated to the latest version of VS2017RC (released yesterday) and it works now.
