### ISSUE TITLE
T4MVC picking wrong route in asp.net MVC 5 routes

### ISSUE THREAD

**Issue by cblaze22** [T4MVC/T4MVC#95]
Any clue why this wont get picked up?  It may not even be a T4MVC issue but it doesnt generate the right URL.

http://stackoverflow.com/questions/42286634/t4mvc-picking-wrong-route-in-asp-net-mvc-5-routes

**Comment by davidebbo** [comment]
I'd suggest trying it without the T4MVC syntax to isolate whether issue is T4MVC related.

**Comment by cblaze22** [comment]
It does work but it looks like it has to do with the page I am on as it works from another page just fine but on this one it is for some reason picking a different route and I think it's because it is using route parameters from the page to build the route instead of mine.

**Comment by cblaze22** [comment]
I fixed it by moving the route above the one being hit, and added seasonid in the actual route which I didnt want to do

**Comment by davidebbo** [comment]
My guess is that this is just a reflection of standard MVC routing behavior (which can certainly be tricky). In the end, T4MVC is just nicer syntax over the same underlying things.
