### ISSUE TITLE
Warning CS0436: The type 'Dummy' in 'Project1' conflicts with the imported type 'Dummy' in 'Project2`

### ISSUE THREAD

**Issue by trailmax** [T4MVC/T4MVC#96]
We have a solution with a few MVC projects inside. Main MVC project and MVC modules auto-discovered. All the projects have T4MVC with different namespace. 

But when building the whole solution I get compiler warnings:

> T4MVC.cs(54,23): warning CS0436: The type 'Dummy' in 'C:\Solution\Module1\T4MVC.cs' conflicts with the imported type 'Dummy' in 'MainProject`.

Basically in every T4MVC there is a `Dummy` (even if in different namespaces) class which is causing this warning. 

It is simple to fix by suppressing warning 0436 in `pragma warning disable` directive on top of .tt file. I'm wondering if it is worth adding this to the project, so on the NuGet update I won't get this written over (does NuGet update for T4MVC updates .tt file?)

**Comment by davidebbo** [comment]
I think the way NuGet works is that the .tt file gets overwritten only if it has not changed from the currently installed package.

**Comment by trailmax** [comment]
I'll need to check the NuGet theory. But in principle, would you consider excluding this warning? Just around `Dummy` class? I can try doing a PR for that

**Comment by davidebbo** [comment]
Sure, that sounds good, thanks.

**Comment by trailmax** [comment]
Awesome! Thank you!

**Comment by zurichero** [comment]
Hi, I just downloaded version 4.0.0.0 using NuGet and I still get this warning message CS0436 because of the Dummy classes?
Is there any workaround available?
Thank you
Roberto

**Comment by trailmax** [comment]
@zurichero I'll look into this tonight. This issue was fixed for us.

**Comment by zurichero** [comment]
Thank you. I fixed it by changing the T4MVCNamespace and the HelperPrefix in the T4MVC.tt.settings.xml.
Now there is no conflict between the classes in the 2 projects anymore.

**Comment by trailmax** [comment]
@zurichero Sorry for the late response. Indeed, if you have the same namespaces for T4MVC in different projects this will give the 0436 warning. I always had different namespaces in different projects, so this never occurred.

Solution would be to either have different namespaces through tt.settings.xml or to put `0436` into this line https://github.com/T4MVC/T4MVC/blob/master/T4MVCHostMvcApp/T4MVC%20Files/T4MVC.tt#L50 and then re-enable on the corresponding line on the bottom of the file. But I'm worried that this will hide other important warnings that you'd like to see. I think this is such an edge case it is not really worth fixing.

@davidebbo what do you think?

**Comment by davidebbo** [comment]
@trailmax When you say *I think this is such an edge case it is not really worth fixing.*, are you referring to the original issue, or to the fact that adding the pragma could mask legit warnings?

**Comment by trailmax** [comment]
@davidebbo by edge case I mean have more than 1 MVC project in a solution with T4MVC; and both T4MVC configured to have the same namespace. 

Though I'm not sure how much of a risk we can get here with masking a real warning.

**Comment by davidebbo** [comment]
@trailmax yep, agree this feels like an edge case. I say we leave it alone and hope though who run into it find this issue so they can self-solve without needing to update.

**Comment by trailmax** [comment]
Agreed!
