### ISSUE TITLE
Ajax post not working in ASP.NET MVC Core 1.1

### ISSUE THREAD

**Issue by dotnetdeveloper786** [T4MVC/T4MVC#98]
Ajax post not working in ASP.NET MVC Core 1.1 it throws 500 Internal Server Error

this is my code

$.ajax({
                type: "POST",
                url: '/RemoteValidation/Json/UpdatePriceCalculate',
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                data: { formvalues: form_values, tablefeaturevalues: tablefeatureval },
                success: function (data) {
                    if (data.pnlStock == false) {
                        $("#pnl_Stock").hide();
                    }
                    else {
                        $("#pnl_Stock").show();
                    }
                    if (data.pnlArtWork == false) {

                        $("#pnl_ArtWork").hide();
                    }
                    else {
                        $("#pnl_ArtWork").show();
                    }
                    if (data.pnlFileVarification == false) {
                        $("#pnl_FileVarification").hide();
                    }
                    else {
                        $("#pnl_FileVarification").show();
                    }
                    if (data.pnlLarge == false) {

                        $("#pnl_Large").hide();
                    }
                    else {
                        $("#pnl_Large").show();
                    }
                    if (data.pnlPurchaseOrder == false) {

                        $("#pnl_PurchaseOrder").hide();
                    }
                    else {
                        $("#pnl_PurchaseOrder").show();
                    }
                    if (data.pnlQty == false) {
                        $("#pnl_Qty").hide();
                    }
                    else {
                        $("#pnl_Qty").show();
                    }
                    if (data.pnlDiscountPanel == false) {
                        $("#pnl_DiscountPanel").hide();
                    }
                    else {
                        $("#pnl_DiscountPanel").show();
                    }

                    $("#tblFeature").html(data.tblFeature);
                    $("#hdnTotalProperty").html(data.hdnTotalProperty);
                    $("#lblSizeName").html(data.lblSizeName);
                    $("#lblCost").html(data.lblCost);
                    $("#lblWeight").html(data.lblWeight);
                    $("#hypFileInfo").attr("title",data.hypFileInfo);
                    $("#lblTotalPrice").html(data.lblTotalPrice);
                    $("#lblPrintingCost").html(data.lblPrintingCost);
                    $("#ddlFileVarfctn").val(data.ddlFileVarfctn);
                    $("#txtHeight").val(data.txtHeight);
                    $("#txtWidth").val(data.txtWidth);
                    $("#lblError").html(data.lblError);
                    $("#lblCostSymbol").html(data.lblCostSymbol);

                    $("#lblDiscountPercentBack").html(data.lblDiscountPercentBack);

                    $("#reqPONo").html(data.reqPONo);
                    $("#hyprInformation").attr("title", data.hyprInformation);
                    $("#lblOriginalAmount").html(data.lblOriginalAmount);
                    $("#lblDiscountPercent").html(data.lblDiscountPercent);
                    $("#lblDiscountAmount").html(data.lblDiscountAmount);
                    $("#lblErrorMsg").html(data.lblErrorMsg);
                    $("#lblOriginalPrice").html(data.lblOriginalPrice);
                    $("#lblSubTotalCost").html(data.lblSubTotalCost);
                    $("#lblFileVerification").html(data.lblFileVerification);
                    $("#lblPrintTurnaround").html(data.lblPrintTurnaround);
                    $("#lblTotalCost").html(data.lblTotalCost);
                    $("#txtPurchaseOrderNumber").val(data.txtPurchaseOrderNumber);
                    $(".ddlPaper").bind("change", function () {
                        UpdatePrice();
                    });
                }
            });

**Comment by davidebbo** [comment]
T4MVC does not support ASP.NET Core. See also #65
